// Generated by CoffeeScript 2.0.0-beta2
this.BoardCreator = class BoardCreator {
  CreateBoard() {
    var i, j, len, locationsSoFar, shipMaker, shipSizes, ships;
    locationsSoFar = [];
    ships = [];
    shipSizes = [2, 3, 3, 4, 5];
    shipSizes.sort(function(a, b) {
      return Math.round(Math.random()) - 0.5;
    });
    for (j = 0, len = shipSizes.length; j < len; j++) {
      i = shipSizes[j];
      shipMaker = new ShipMaker({
        length: i,
        locationsSoFar: locationsSoFar
      });
      ships.push({
        Fields: shipMaker.MakeShip()
      });
    }
    return ships;
  }

};
