// Generated by CoffeeScript 2.0.0-beta2
$("#startgame").click(function() {
  return $.ajax({
    url: 'http://localhost:50095/Register',
    type: 'POST',
    data: {
      GameId: $('#gameid').val(),
      PlayerId: $('#playerid').val(),
      Url: window.location.href,
      BattleShips: new BoardCreator().CreateBoard()
    },
    dataType: "json",
    success: function(response) {
      return alert("success");
    },
    error: function(xhr, status) {
      return alert("error");
    }
  });
});
